@Qualifier
Annotated the setter with @Qualifier & defined bean with Qualifer
Also, added the context namespace
Exception :
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'healthChecker': Injection of autowired dependencies
failed; nested exception is
org.springframework.beans.factory.BeanCreationException: Could not
autowire method: public void
in.mhatre.sagar.spring.core.beans.HealthChecker.setDbConnector(in.mhatre.sagar.spring.core.beans.DBConnector);
nested exception is
org.springframework.beans.factory.NoUniqueBeanDefinitionException: No
qualifying bean of type [in.mhatre.sagar.spring.core.beans.DBConnector]
is defined: expected single matching bean but found 3:
myDBConnector,renamed_dbConnector,qualifiedConnector